[en]
    weight = 1
    contentDir = "content/english"
    languageName = "English"
    [en.params]
        slogan = ""
        description = ""
        siteTitle = ""
        siteDescription = ""
        twitter = "https://x.com/_atomone"
        github = "https://github.com/atomone-hub"
